importing necessary libraries

In [191]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [192]:
data = pd.read_csv('../data/data.csv')

In [193]:
data.head()

Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0    M                298.1                    308.6                    1551   
1    L                298.2                    308.7                    1408   
2    L                298.1                    308.5                    1498   
3    L                298.2                    308.6                    1433   
4    L                298.2                    308.7                    1408   

   Torque [Nm]  Tool wear [min]  Target  
0         42.8                0       0  
1         46.3                3       0  
2         49.4                5       0  
3         39.5                7       0  
4         40.0                9       0

encoding the Type column using map function 

In [194]:
data['Type'] = data.Type.map({'L':0, 'M':1, 'H':2})

In [195]:
data.head()

Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0     1                298.1                    308.6                    1551   
1     0                298.2                    308.7                    1408   
2     0                298.1                    308.5                    1498   
3     0                298.2                    308.6                    1433   
4     0                298.2                    308.7                    1408   

   Torque [Nm]  Tool wear [min]  Target  
0         42.8                0       0  
1         46.3                3       0  
2         49.4                5       0  
3         39.5                7       0  
4         40.0                9       0

scaling data 

In [196]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Type                     10000 non-null  int64  
 1   Air temperature [K]      10000 non-null  float64
 2   Process temperature [K]  10000 non-null  float64
 3   Rotational speed [rpm]   10000 non-null  int64  
 4   Torque [Nm]              10000 non-null  float64
 5   Tool wear [min]          10000 non-null  int64  
 6   Target                   10000 non-null  int64  
dtypes: float64(3), int64(4)
memory usage: 547.0 KB


In [197]:
data = data.astype(float)


In [198]:
x = data.drop('Target', axis=1)
y = data.Target

In [199]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x = scaler.fit_transform(x)

In [200]:
x

array([[ 0.74441274, -0.95238944, -0.94735989,  0.06818514,  0.28219976,
        -1.69598374],
       [-0.74530658, -0.90239341, -0.879959  , -0.72947151,  0.63330802,
        -1.6488517 ],
       [-0.74530658, -0.95238944, -1.01476077, -0.22744984,  0.94428963,
        -1.61743034],
       ...,
       [ 0.74441274, -0.50242514, -0.94735989,  0.59251888, -0.66077672,
        -1.35034876],
       [ 2.23413206, -0.50242514, -0.879959  , -0.72947151,  0.85400464,
        -1.30321671],
       [ 0.74441274, -0.50242514, -0.879959  , -0.2162938 ,  0.02137647,
        -1.22466331]])

In [201]:
y

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
9995    0.0
9996    0.0
9997    0.0
9998    0.0
9999    0.0
Name: Target, Length: 10000, dtype: float64

In [202]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [203]:
X_train

array([[-0.74530658, -0.85239738, -0.61035546,  0.43075634, -0.89150501,
         1.36759909],
       [-0.74530658, -0.90239341, -1.08216166, -0.84103188,  1.38568287,
         0.45637958],
       [-0.74530658, -0.90239341, -1.48656697, -0.06010929, -0.89150501,
         1.35188841],
       ...,
       [ 2.23413206,  1.39742414,  1.54647288, -0.31112012,  0.723593  ,
         1.80749816],
       [ 2.23413206, -1.95231012, -2.09317494,  0.01240496, -0.74103004,
        -1.17753127],
       [-0.74530658,  0.09752726,  0.26585605,  1.50173589, -1.42318324,
        -1.1461099 ]])

In [204]:
X_test

array([[-7.45306575e-01,  3.97503465e-01,  1.98455168e-01,
        -4.32910016e-03, -3.89921778e-01,  1.41473113e+00],
       [ 7.44412743e-01,  1.79739241e+00,  1.20946845e+00,
        -6.56957265e-01,  4.82833050e-01, -1.09204945e-01],
       [ 7.44412743e-01, -8.52397376e-01, -1.41916609e+00,
        -2.99964081e-01,  2.01946439e-01,  1.42165954e-01],
       ...,
       [-7.45306575e-01,  1.47523296e-01,  1.14206757e+00,
        -1.23707119e+00,  1.65653782e+00, -1.58600898e+00],
       [-7.45306575e-01, -1.55234185e+00, -1.68876963e+00,
         6.59446679e+00, -3.07840791e+00, -1.41319148e+00],
       [ 7.44412743e-01,  4.97495532e-01,  1.07466668e+00,
        -1.32631948e+00,  1.50606285e+00, -1.55458761e+00]])

In [205]:
y_train

9254    0.0
1561    0.0
1670    0.0
6087    0.0
6669    0.0
       ... 
5734    1.0
5191    0.0
5390    0.0
860     0.0
7270    0.0
Name: Target, Length: 8000, dtype: float64

In [206]:
y_test

6252    0.0
4684    1.0
1731    0.0
4742    0.0
4521    0.0
       ... 
6412    0.0
8285    0.0
7853    0.0
1095    1.0
6929    0.0
Name: Target, Length: 2000, dtype: float64

In [207]:
from sklearn.ensemble import RandomForestClassifier

In [208]:
rfc = RandomForestClassifier()

In [209]:
model = rfc.fit(X_train,y_train)

In [210]:
y_pred = rfc.predict(X_test)

In [211]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.984


In [212]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.973


In [213]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train,y_train)
y_pred = dtc.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9785


In [214]:
import pickle 
pickle.dump(model, open('model.pkl', 'wb'))
