In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('C:\git\-Predictive-Maintenance-for-Industrial-Equipment\data\predictive_maintenance.csv')

In [5]:
df.head()

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target Failure Type  
0                    1551         42.8                0       0   No Failure  
1                    1408         46.3                3       0   No Failure  
2                    1498         49.4                5       0   No Failure  
3                    1433         39.5                7       0   No Failure  
4                    1408         40.0                9       0   No Failure

In [6]:
df['Type'] = df.Type.map({'L':0, 'M':1, 'H':2})
df.drop(['UDI', 'Product ID','Failure Type'], axis=1, inplace=True)

In [7]:
df.head()

Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0     1                298.1                    308.6                    1551   
1     0                298.2                    308.7                    1408   
2     0                298.1                    308.5                    1498   
3     0                298.2                    308.6                    1433   
4     0                298.2                    308.7                    1408   

   Torque [Nm]  Tool wear [min]  Target  
0         42.8                0       0  
1         46.3                3       0  
2         49.4                5       0  
3         39.5                7       0  
4         40.0                9       0

In [8]:
df = df.astype(float)
x = df.drop('Target', axis=1)
y = df.Target


In [9]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()
x = scaler.fit_transform(x)


In [10]:
x


array([[6.21186146e-04, 1.85175590e-01, 1.91698045e-01, 9.63459713e-01,
        2.65867671e-02, 0.00000000e+00],
       [0.00000000e+00, 2.02485683e-01, 2.09615460e-01, 9.56069219e-01,
        3.14389239e-02, 2.03707930e-03],
       [0.00000000e+00, 1.91211363e-01, 1.97882273e-01, 9.60867567e-01,
        3.16868210e-02, 3.20716811e-03],
       ...,
       [5.88005374e-04, 1.75813607e-01, 1.81458458e-01, 9.67268840e-01,
        1.96393795e-02, 1.29361182e-02],
       [1.35764407e-03, 2.02967788e-01, 2.09552362e-01, 9.55781422e-01,
        3.29228686e-02, 1.69705508e-02],
       [6.40550231e-04, 1.91524519e-01, 1.97737856e-01, 9.60825346e-01,
        2.57501193e-02, 1.92165069e-02]])

In [11]:
y

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
9995    0.0
9996    0.0
9997    0.0
9998    0.0
9999    0.0
Name: Target, Length: 10000, dtype: float64

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [13]:
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=[6]),
    layers.Dense(64, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])



In [14]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10


250/250 [==============================] - 2s 3ms/step - loss: 0.1801 - accuracy: 0.9653 - val_loss: 0.1363 - val_accuracy: 0.9695
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.1506 - accuracy: 0.9653 - val_loss: 0.1347 - val_accuracy: 0.9695
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.1482 - accuracy: 0.9653 - val_loss: 0.1342 - val_accuracy: 0.9695
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.1450 - accuracy: 0.9653 - val_loss: 0.1277 - val_accuracy: 0.9695
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.1408 - accuracy: 0.9653 - val_loss: 0.1227 - val_accuracy: 0.9695
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.1357 - accuracy: 0.9653 - val_loss: 0.1184 - val_accuracy: 0.9695
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.1317 - accuracy: 0.9653 - val_loss: 0.1269 - val_accuracy: 0.9695
Epoc

In [19]:
y_pred = model.predict(x_test)
y_pred = [1 if y>=0.5 else 0 for y in y_pred]

63/63 [==============================] - 0s 1ms/step


array([[1938,    1],
       [  59,    2]], dtype=int64)

In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Calculate precision
precision = precision_score(y_test, y_pred)

# Calculate recall
recall = recall_score(y_test, y_pred)

# Calculate F1 score
f1 = f1_score(y_test, y_pred)

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 score: {f1}")
print(f"Confusion matrix:\n{conf_matrix}")

Accuracy: 0.97
Precision: 0.6666666666666666
Recall: 0.03278688524590164
F1 score: 0.0625
Confusion matrix:
[[1938    1]
 [  59    2]]
